name: Generate Sitemap

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  sitemap:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate Sitemap
        run: node generate-sitemap.js

      - name: Commit Sitemap
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add sitemap.xml

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Auto Generate Sitemap"
            git push
          fi
